server:
  port: 8081

spring:
  application:
    name: incident-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:incidentdb}
    username: ${MYSQL_USER:opsboard}
    password: ${MYSQL_PASSWORD:opsboard_pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
